# Generated by Django 3.0 on 2019-12-05 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=570)),
                ('preferred_analytics', models.CharField(choices=[('PEDESTRIAN', 'Pedestrian Analytics'), ('VEHICLE', 'Vehicle Classification'), ('ALL', 'All')], max_length=100)),
                ('title', models.CharField(max_length=270)),
                ('rtvsp_url', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 16, 36, 21, 635960))),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
